### ISSUE TITLE
Form off centre

### ISSUE THREAD

**Issue by matthewdking** [FACN3/al-shams#57]
I'm not sure what the reasoning behind an off centre form is?
```css
form {
  position: absolute;
  top: 50%;
  left: 40%;
}
```
Maybe use flexbox to centre it instead?
